CREATE WAREHOUSE IF NOT EXISTS RAG_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS RAG_DEMO;
CREATE SCHEMA IF NOT EXISTS RAG_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS RAG_DEMO.ANALYTICS;

-- dbt seed creates RAG_DEMO.RAW.RAW_ORDERS and dbt build creates the marts.
-- Suspend when the demo is finished to avoid unnecessary credit use.
ALTER WAREHOUSE RAG_WH SUSPEND;
